# Generated by Django 5.2 on 2025-04-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('password', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
